### PR TITLE
Create request.R

### PR DESCRIPTION
**Pull request by RakeshKumarA**
Hello I am Trying to install tidyverse dependency, but im struggling for few days with openssl mutual dependency. Is there a way you can help me?

### CODE REVIEW

**Comment by virtualstaticvoid** [comment]
Hi @RakeshKumarA 

Would you be able to share your Dockerfile, or the instructions you are using to install tidyverse?

Thanks

**Comment by RakeshKumarA** [comment]
Repository: https://github.com/RakeshKumarA/deployR7
Objective: To use tidyverse and eventually tidyquant for making stock analysis using apis.
Step1: Cloned https://github.com/virtualstaticvoid/heroku-docker-r-plumber-app
Step2: Created a renv environment, and created a new snapshot with tidyverse and all it's dependencies in renv.lock file.
Step3: Pushed to Heroku git push heroku master
Step4: Added an Aptfile to add commands so that openssl and XML2 gets installed, which failed without Aptfile.
step5: By the time it installs all the dependencies, heroku times out.


Ideally, as you have made, i want to have dependency, part of docker image itself and have a private repo in dockerhub, 
but i'm not aware of the process how to go about that! If you can give me steps of instructions using your main repo, https://github.com/virtualstaticvoid/heroku-docker-r that would be even better

Screenshot 2021-07-04 103759

**Comment by virtualstaticvoid** [comment]
Hi @RakeshKumarA 

I've created a [PR to your example repository](https://github.com/RakeshKumarA/deployR7/pull/1) with the changes necessary.

Your project contains a significant number of packages, so I've introduced a base image to build in `libssl-dev`, `libxml2-dev` and `libsodium-dev` together with the `renv` packages. The base image will need to be published to a registry before you can do the application deployment to Heroku.

Having the base image pre-built will speed up the deployment to Heroku so you shouldn't get the compile timeout error.

The base image can be pushed to a public registry, such as Docker Hub, as it doesn't contain any of your application code, other than the `renv.lock` file. Thus you shouldn't need a private registry in this example, since the base image will only contain already public content.

Hope this helps.

**Comment by RakeshKumarA** [comment]
This is really great! Your help is greatly appreciated. Is there a way I can buy you a coffee?

**Comment by virtualstaticvoid** [comment]
> Is there a way I can buy you a coffee?

This is a first for me. You can use https://www.buymeacoffee.com/cstefano if you like.

Thanks!

**Pull request closed without merging**
